function init(self)
	local current = go.get_position('.')
	local component = "#cell"
	local padding = 30
	local sell_size = 100
	

	local i = 1
	local delta = padding + sell_size
	for x = 1,3 do
		for y = 1,3 do
			local id = factory.create(component, vmath.vector3(current.x + x*delta, current.y + y*delta, 0), nil, { id = i, size = sell_size}, nil) -- <1>
			msg.post(id .. '#cell', "init", {reciver = '/level_logic#controller'})
			i = i + 1
		end
	end
end