function init(self)
	local current = go.get_position('.')
	local component = "#cell"
	local padding = 30
	local sell_size = 100
	local controller_hash = '/level_logic#controller'

	local i = 1
	local delta = padding + sell_size
	for x = 1,3 do
		for y = 1,3 do
			factory.create(component, vmath.vector3(current.x + x*delta, current.y + y*delta, 0), nil, { id = i, controler_url = hash(controller_hash) }, nil) -- <1>
			i = i + 1
		end
	end
end