function init(self)
	self.state = 1
end

function on_message(self, message_id, message, sender)
	if(message_id == hash("change")) then
		self.state =  message.value
	end
end

function update(self, dt)
	local value = self.state
		if value > 1 then 	 
		msg.post("#sprite", "play_animation", {id = hash("p2")})
		elseif value < 1 then
			msg.post("#sprite", "play_animation", {id = hash("p1")}) 
		end
	end
